
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lahiru
 */
public class CreateBranch extends javax.swing.JFrame {

    /**
     * Creates new form CreateBranch
     */
    public CreateBranch() throws SQLException {
        initComponents();
        DisplayTable();
        BranchCode();
    }
    
     public void BranchCode() throws SQLException{
        String query = "SELECT MAX(BID)FROM branch ";
            PreparedStatement ps = null;
            ResultSet rs = null;
            ps = DBConnection.con().prepareStatement(query);
            rs = ps.executeQuery();
            if(rs.next()){
            rs.getString("MAX(BID)");
            
            if(rs.getString("MAX(BID)")==null){
                jTextField4.setText("B001");
            }else{
               
                
                String id=String.valueOf(rs.getString("MAX(BID)"));
             
                String id1=id.substring(0,1);
                String id2=id.substring(2,4);
               long n= Long.parseLong(id2);
                n++;
                String num1=Long.toString(n);
                jTextField4.setText(id1+String.format("%03d",n));
            }
            }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 630));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Branch", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel8.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(jLabel9);
        jLabel9.setBounds(640, 30, 110, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(jLabel10);
        jLabel10.setBounds(740, 30, 110, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                " Code", "Name", "Address", "TP", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel8.add(jScrollPane2);
        jScrollPane2.setBounds(20, 290, 770, 180);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);
        jPanel3.add(jTextField4);
        jTextField4.setBounds(120, 20, 220, 30);
        jPanel3.add(jTextField5);
        jTextField5.setBounds(120, 70, 220, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Branch code:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 20, 90, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Name :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 70, 70, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Address :");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(20, 110, 90, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("TP:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(20, 160, 70, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("E mail :");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(20, 210, 70, 30);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(120, 210, 220, 30);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField7);
        jTextField7.setBounds(120, 160, 220, 30);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(120, 110, 220, 30);

        jPanel8.add(jPanel3);
        jPanel3.setBounds(10, 20, 410, 260);

        jButton13.setText("ADD");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton13);
        jButton13.setBounds(520, 100, 90, 40);

        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4);
        jButton4.setBounds(520, 170, 90, 40);

        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5);
        jButton5.setBounds(640, 170, 90, 40);

        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2);
        jButton2.setBounds(640, 100, 90, 40);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(170, 90, 810, 490);

        jPanel1.setBackground(new java.awt.Color(33, 97, 97));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("HEWAGE SUPER");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 20, 320, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(900, 20, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 80);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(null);

        jButton12.setText("CREATE USER");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12);
        jButton12.setBounds(10, 20, 130, 30);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(0, 50, 160, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ADMINISTRATION");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 20, 150, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 160, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void DisplayTable(){
        try {
            String query ="SELECT * FROM branch ";
            PreparedStatement ps=null;
            ResultSet rs=null;
            
            ps=DBConnection.con().prepareStatement(query);
            rs=ps.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(CUSTOMER.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            CreateUser c= new CreateUser();
            c.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(CreateBranch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Administration a= new Administration();
        a.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        PreparedStatement ps=null;
        ResultSet rs1=null;
        ResultSet rs2=null;

        
       
        //String g=String.valueOf(jComboBox1.getSelectedItem());
        
        //checking email address
        
        String email_pattern = "^[a-zA-Z0-9]{1,20}@[a-zA-Z0-9]{1,20}.[a-zA-Z]{2,3}$";
        Pattern patrn = Pattern.compile(email_pattern);
        Matcher regxmatcher = patrn.matcher(jTextField8.getText());
        if(!regxmatcher.matches()){
            JOptionPane.showMessageDialog(null, "Invalid Email format!","", JOptionPane.WARNING_MESSAGE, UIManager.getIcon("OptionPane.warningIcon"));
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
        
        }
        
        
        
        if(jTextField7.getText().length()<10){
          JOptionPane.showMessageDialog(null, "Invalid  Telephone Number!","", JOptionPane.WARNING_MESSAGE, UIManager.getIcon("OptionPane.warningIcon"));  
        }
        String a=jTextField4.getText();
        String b=jTextField5.getText();
        String c=jTextField6.getText();
        String d=jTextField7.getText();
        String e=jTextField8.getText();
        
        if(a.equals("") || b.equals("") || c.equals("") || d.equals("") ){
            JOptionPane.showMessageDialog(this, "Please Fill all Fields Correctly !");
            //this.setVisible(false);
        } else{
            try {
                String query_A="SELECT * FROM `branch` WHERE BID=? ";
                ps=DBConnection.con().prepareStatement(query_A);
                ps.setString(1, a);
                rs1=ps.executeQuery();

                if(rs1.next()){
                    JOptionPane.showMessageDialog(this,"Invalid BID");
                }
                else{
                    String query= "INSERT INTO `branch`"
                    +"(`BID`, `Name`, `Address`, `Email`, `Tp`)"
                    +"VALUES (?,?,?,?,?)";
                    ps=DBConnection.con().prepareStatement(query);

                    ps.setString(1,a);
                    ps.setString(2,b);
                    ps.setString(3,c);
                    ps.setString(4,e);
                    ps.setString(5,d);
                    

                    ps.execute();

                    JOptionPane.showMessageDialog(this, "New Branch has added!");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    DisplayTable();

                }
            } catch (SQLException ex) {
                Logger.getLogger(CUSTOMER.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PreparedStatement ps=null;
        ResultSet rs1=null;
        
        
         String email_pattern = "^[a-zA-Z0-9]{1,20}@[a-zA-Z0-9]{1,20}.[a-zA-Z]{2,3}$";
        Pattern patrn = Pattern.compile(email_pattern);
        Matcher regxmatcher = patrn.matcher(jTextField8.getText());
        if(!regxmatcher.matches()){
            JOptionPane.showMessageDialog(null, "Invalid Email format!","", JOptionPane.WARNING_MESSAGE, UIManager.getIcon("OptionPane.warningIcon"));
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
        
        }
        
        
        
        if(jTextField7.getText().length()<10){
          JOptionPane.showMessageDialog(null, "Invalid  Telephone Number!","", JOptionPane.WARNING_MESSAGE, UIManager.getIcon("OptionPane.warningIcon"));  
        }
        String a=jTextField4.getText();
        String b=jTextField5.getText();
        String c=jTextField6.getText();
        String d=jTextField7.getText();
        String e=jTextField8.getText();
        

      
        //String g=String.valueOf(jComboBox1.getSelectedItem());

        if(a.equals("") || b.equals("") || c.equals("") || d.equals("") ){
            JOptionPane.showMessageDialog(this, "Please Fill all Fields !");
            //this.setVisible(false);
        } else{
            try {
                    String query= "UPDATE `branch` SET `Name`=?,`Address`=?,`Email`=?,`Tp`=? WHERE BID=?";
                    ps=DBConnection.con().prepareStatement(query);

                    ps.setString(1,b);
                    ps.setString(2,c);
                    ps.setString(3,e);
                    ps.setString(4,d);
                    ps.setString(5,a);
                    

                    ps.execute();

                    JOptionPane.showMessageDialog(this, "Updated!");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                   
                    DisplayTable();
                
            } catch (SQLException ex) {
                Logger.getLogger(CUSTOMER.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String a= jTextField4.getText();
            String query ="SELECT  * FROM  `branch`  WHERE BID = ? ";
            PreparedStatement ps=null;
            ResultSet rs=null;
            ps=DBConnection.con().prepareStatement(query);
            ps.setString(1, a);
            rs=ps.executeQuery();
            if(rs.next()){

                jTextField5.setText(rs.getString("Name"));
                jTextField6.setText(rs.getString("Address"));
                jTextField7.setText(rs.getString("TP"));
                jTextField8.setText(rs.getString("Email"));
            }
            else{
                JOptionPane.showMessageDialog(this, "Branch Not Found!");
                jTextField4.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CUSTOMER.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
           String ph=jTextField7.getText();
      
      int len=ph.length();
      char c= evt.getKeyChar();
      // check the character
      if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
          
      if(len<10){
      jTextField7.setEditable(true);
      }else{
      jTextField7.setEditable(false);
      
      }
      }
      else{
      //erase number 'backspace work'
      if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
          // allo edit
          jTextField7.setEditable(true);
      }else{
           jTextField7.setEditable(false);
      }
      }
    }//GEN-LAST:event_jTextField7KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CreateBranch().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CreateBranch.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
