
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lahiru
 */
public class CUSTOMER extends javax.swing.JFrame {

    /**
     * Creates new form CUSTOMER
     */
    public CUSTOMER() {
        initComponents();
        DisplayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 630));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(33, 97, 97));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("HEWAGE SUPER");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 20, 320, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(900, 20, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 80);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(null);

        jButton11.setText("Customer details");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11);
        jButton11.setBounds(20, 20, 120, 30);

        jButton10.setText("Promotions");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10);
        jButton10.setBounds(20, 60, 120, 30);

        jButton12.setText("Barcode Generate");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12);
        jButton12.setBounds(20, 100, 120, 30);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(0, 50, 160, 150);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 160, 540);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NEW CUSTOMER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel8.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(jLabel10);
        jLabel10.setBounds(740, 30, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("First Name :");
        jPanel8.add(jLabel6);
        jLabel6.setBounds(30, 60, 70, 30);
        jPanel8.add(jTextField1);
        jTextField1.setBounds(110, 60, 250, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Last Name :");
        jPanel8.add(jLabel7);
        jLabel7.setBounds(30, 100, 70, 30);
        jPanel8.add(jTextField2);
        jTextField2.setBounds(110, 100, 250, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Gender :");
        jPanel8.add(jLabel8);
        jLabel8.setBounds(30, 180, 70, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("TP :");
        jPanel8.add(jLabel11);
        jLabel11.setBounds(460, 20, 50, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel8.add(jTextField3);
        jTextField3.setBounds(540, 20, 220, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("NIC :");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(30, 20, 70, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel8.add(jTextField4);
        jTextField4.setBounds(110, 20, 180, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Address :");
        jPanel8.add(jLabel13);
        jLabel13.setBounds(460, 70, 70, 30);
        jPanel8.add(jTextField5);
        jTextField5.setBounds(540, 70, 220, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("E mail :");
        jPanel8.add(jLabel14);
        jLabel14.setBounds(460, 120, 70, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField6);
        jTextField6.setBounds(540, 120, 220, 30);

        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4);
        jButton4.setBounds(350, 240, 90, 40);

        jButton13.setText("ADD");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton13);
        jButton13.setBounds(220, 240, 90, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIC", "First name", "Last Name", "Gender", "TP", "Address", "E mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel8.add(jScrollPane1);
        jScrollPane1.setBounds(30, 300, 770, 150);

        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5);
        jButton5.setBounds(470, 240, 90, 40);

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2);
        jButton2.setBounds(290, 20, 70, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButton1);
        jRadioButton1.setBounds(110, 190, 60, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButton2);
        jRadioButton2.setBounds(190, 190, 93, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Branch ID :");
        jPanel8.add(jLabel2);
        jLabel2.setBounds(30, 130, 80, 50);

        jPanel8.add(jComboBox1);
        jComboBox1.setBounds(110, 140, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Registered By :");
        jPanel8.add(jLabel3);
        jLabel3.setBounds(450, 170, 90, 30);

        jPanel8.add(jComboBox2);
        jComboBox2.setBounds(540, 170, 160, 30);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(170, 90, 820, 470);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void DisplayTable(){
        try {
            String query ="SELECT * FROM customer WHERE NIC <> 0 ";
            PreparedStatement ps=null;
            ResultSet rs=null;
            
            ps=DBConnection.con().prepareStatement(query);
            rs=ps.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(CUSTOMER.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PreparedStatement ps=null;
            ResultSet rs1=null;
            ResultSet rs2=null;
            
             String email_pattern = "^[a-zA-Z0-9]{1,20}@[a-zA-Z0-9]{1,20}.[a-zA-Z]{2,3}$";
        Pattern patrn = Pattern.compile(email_pattern);
        Matcher regxmatcher = patrn.matcher(jTextField6.getText());
        if(!regxmatcher.matches()){
            JOptionPane.showMessageDialog(null, "Invalid Email format!","", JOptionPane.WARNING_MESSAGE, UIManager.getIcon("OptionPane.warningIcon"));
           // jTextField4.setText("");
            //jTextField5.setText("");
            //jTextField6.setText("");
           // jTextField7.setText("");
            //jTextField8.setText("");
        
        }
        
        
        
        if(jTextField3.getText().length()<10){
          JOptionPane.showMessageDialog(null, "Invalid  Telephone Number!","", JOptionPane.WARNING_MESSAGE, UIManager.getIcon("OptionPane.warningIcon"));  
        }
            
            
            String a=jTextField4.getText();
            String b=jTextField1.getText();
            String c=jTextField2.getText();
            String d=jTextField3.getText();
            String e=jTextField5.getText();
            String f=jTextField6.getText();
            String g="";
            if(jRadioButton1.isSelected()){
                 g="Male";
            }else{
                g="Female";
            }
             String k=String.valueOf(jComboBox2.getSelectedItem());
             String l=String.valueOf(jComboBox1.getSelectedItem());
            //String g=String.valueOf(jComboBox1.getSelectedItem());
             String dte = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
            
            if(a.equals("") || b.equals("") || c.equals("") || d.equals("") || f.equals("") || g.equals("")  || k.equals("") ){
               JOptionPane.showMessageDialog(this, "Please Fill all Fields !");
               
            } else{  
            try {
                String query_A="SELECT * FROM `customer` WHERE NIC=? ";
                ps=DBConnection.con().prepareStatement(query_A);
                ps.setString(1, a);
                rs1=ps.executeQuery();
                
                if(rs1.next()){
                    String query= "UPDATE  `customer` SET `FirstName`=?, `LastName`=?, `Email`=?, `Gender`=?, `TP`=?, `Address`=?,`BranchID`=?, `RegisterdDate`=?, `RegisteredBy`=? WHERE `NIC`=?";
                           
                    ps=DBConnection.con().prepareStatement(query);
                    
                    
                    ps.setString(1,b);
                    ps.setString(2,c);
                    ps.setString(3,f);
                    ps.setString(4,g);
                    ps.setString(5,d);
                    ps.setString(6,e);
                    ps.setString(7,l);
                    ps.setString(8,dte);
                    ps.setString(9,k);
                    ps.setString(10,a);
                    
                   
                    
                    ps.execute();
                    
                    JOptionPane.showMessageDialog(this, "Updated!");
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jRadioButton1.setSelected(false);
                    jRadioButton2.setSelected(false);
                    DisplayTable();
                }else{
                    JOptionPane.showMessageDialog(this, "Invalid NIC!");
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(CUSTOMER.class.getName()).log(Level.SEVERE, null, ex);
            }
            }   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jRadioButton1.setSelected(false);
                    jRadioButton2.setSelected(false);
                    jComboBox1.setSelectedItem(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String a= jTextField4.getText();
            String query ="SELECT  * FROM `customer`  WHERE NIC = ? ";
            PreparedStatement ps=null;
            ResultSet rs=null;
            ps=DBConnection.con().prepareStatement(query);
            ps.setString(1, a);
            rs=ps.executeQuery();
            if(rs.next()){
                
                jTextField1.setText(rs.getString("FirstName"));
                jTextField2.setText(rs.getString("LastName"));
                jTextField5.setText(rs.getString("Address"));
                jTextField3.setText(rs.getString("TP"));
                jTextField6.setText(rs.getString("Email"));
                jComboBox1.setSelectedItem(rs.getString("BranchID"));
                jComboBox2.setSelectedItem(rs.getString("RegisteredBy"));
                
                
               
                if(rs.getString("Gender").equals("Male")){
                    jRadioButton1.setSelected(true);
                }else if(rs.getString("Gender").equals("Female")){
                    jRadioButton2.setSelected(true);
                }
                //jComboBox1.setSelectedItem(rs.getString("Gender"));
              
                
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Customer Not Found!");
                jTextField4.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CUSTOMER.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
            PreparedStatement ps=null;
            ResultSet rs1=null;
            ResultSet rs2=null;
            
            String dte = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
            
             //checking email address
        
        String email_pattern = "^[a-zA-Z0-9]{1,20}@[a-zA-Z0-9]{1,20}.[a-zA-Z]{2,3}$";
        Pattern patrn = Pattern.compile(email_pattern);
        Matcher regxmatcher = patrn.matcher(jTextField6.getText());
        if(!regxmatcher.matches()){
            JOptionPane.showMessageDialog(null, "Invalid Email format!","", JOptionPane.WARNING_MESSAGE, UIManager.getIcon("OptionPane.warningIcon"));
           // jTextField4.setText("");
            //jTextField5.setText("");
            //jTextField6.setText("");
           // jTextField7.setText("");
            //jTextField8.setText("");
        
        }
        
        
        
        if(jTextField3.getText().length()<10){
          JOptionPane.showMessageDialog(null, "Invalid  Telephone Number!","", JOptionPane.WARNING_MESSAGE, UIManager.getIcon("OptionPane.warningIcon"));  
        }
        
            String a=jTextField4.getText();
            String b=jTextField1.getText();
            String c=jTextField2.getText();
            String d=jTextField3.getText();
            String e=jTextField5.getText();
            String f=jTextField6.getText();
            String h=String.valueOf(jComboBox1.getSelectedItem());
            String g="";
            if(jRadioButton1.isSelected()){
                 g="Male";
            }else{
                g="Female";
            }
            String k=String.valueOf(jComboBox2.getSelectedItem());
            //String g=String.valueOf(jComboBox1.getSelectedItem());
            
            
            if(a.equals("") || b.equals("") || c.equals("") || d.equals("") || f.equals("") || g.equals("") || h.equals("") || k.equals("")){
               JOptionPane.showMessageDialog(this, "Please Fill all Fields !");
              
            } else{  
            try {
                String query_A="SELECT * FROM `customer` WHERE NIC=? ";
                ps=DBConnection.con().prepareStatement(query_A);
                ps.setString(1, a);
                rs1=ps.executeQuery();
                
                if(rs1.next()){
                    JOptionPane.showMessageDialog(this,"Invalid NIC");
                }
                else{
                    String query= "INSERT INTO `customer`"
                            +"(`FirstName`, `LastName`, `Email`, `NIC`, `Gender`, `TP`, `Address`,`BranchID`,`RegisterdDate`,`RegisteredBy`, `LoyaltyPoints`)"
                            +"VALUES (?,?,?,?,?,?,?,?,?,?,?)";
                    ps=DBConnection.con().prepareStatement(query);
                    
                    
                    ps.setString(1,b);
                    ps.setString(2,c);
                    ps.setString(3,f);
                    ps.setString(4,a);
                    ps.setString(5,g);
                    ps.setString(6,d);
                    ps.setString(7,e);
                    ps.setString(8,h);
                    ps.setString(9,dte);
                     ps.setString(10,k);
                    ps.setString(11,"0");
                   
                    
                    ps.execute();
                    
                    JOptionPane.showMessageDialog(this, "New Customer has added!");
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jComboBox1.setSelectedItem(null);
                    
                    jRadioButton1.setSelected(false);
                    jRadioButton2.setSelected(false);
                   DisplayTable();
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(CUSTOMER.class.getName()).log(Level.SEVERE, null, ex);
            }
            }   
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Billing ab= new Billing();
            ab.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(CUSTOMER.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
       
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try {
            PreparedStatement ps= null;
            ResultSet rs= null;
            
            String query="SELECT * FROM branch ";
            ps=DBConnection.con().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
                jComboBox1.addItem(rs.getString("BID"));
             }  
            
            String query1="SELECT * FROM employee ";
               ps=DBConnection.con().prepareStatement(query1);
               rs=ps.executeQuery();
               while(rs.next()){
                   jComboBox2.addItem(rs.getString("EID"));
               }
            
        } catch (SQLException ex) {
            Logger.getLogger(CUSTOMER.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        String ph=jTextField3.getText();
      
      int len=ph.length();
      char c= evt.getKeyChar();
      // check the character
      if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
          
      if(len<10){
      jTextField3.setEditable(true);
      }else{
      jTextField3.setEditable(false);
      
      }
      }
      else{
      //erase number 'backspace work'
      if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
          // allo edit
          jTextField3.setEditable(true);
      }else{
           jTextField3.setEditable(false);
      }
      }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        CustomerDetails s = new CustomerDetails();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        EmployeePromotion a= new EmployeePromotion();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        barcode  c = new barcode();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
          String ph=jTextField4.getText();
      
      int len=ph.length();
      char c= evt.getKeyChar();
      // check the character
      if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9' || evt.getExtendedKeyCode()==KeyEvent.VK_V){
          
      if(len<10){
      jTextField4.setEditable(true);
      }else{
      jTextField4.setEditable(false);
      
      }
      }
      else{
      //erase number 'backspace work'
      if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
          // allo edit
          jTextField4.setEditable(true);
      }else{
           jTextField4.setEditable(false);
      }
      }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CUSTOMER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
