
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lahiru
 */
public class Promotions extends javax.swing.JFrame {

    /**
     * Creates new form Promotions
     */
    public Promotions() {
        initComponents();
        DisplayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton13 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(33, 97, 97));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("HEWAGE SUPER");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 20, 320, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(900, 20, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 80);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(null);

        jButton11.setText("Stock");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11);
        jButton11.setBounds(20, 60, 110, 30);

        jButton10.setText("Items");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10);
        jButton10.setBounds(20, 20, 110, 30);

        jButton12.setText("Reports");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12);
        jButton12.setBounds(20, 100, 110, 30);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(0, 20, 160, 160);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 160, 540);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Promotions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel8.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(jLabel9);
        jLabel9.setBounds(640, 30, 110, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(jLabel10);
        jLabel10.setBounds(740, 30, 110, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                " Code", "Name", "Address", "TP", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel8.add(jScrollPane2);
        jScrollPane2.setBounds(20, 300, 770, 170);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jPanel3.add(jTextField4);
        jTextField4.setBounds(120, 60, 220, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Code:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(30, 60, 90, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Name :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(30, 20, 70, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("From :");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 110, 60, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("To:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 150, 19, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("New Unit Prize :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 180, 90, 30);
        jPanel3.add(jDateChooser1);
        jDateChooser1.setBounds(120, 100, 220, 30);
        jPanel3.add(jDateChooser2);
        jDateChooser2.setBounds(120, 140, 220, 30);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(120, 180, 220, 30);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(120, 20, 220, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Status :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 220, 70, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Closed" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(120, 220, 160, 30);

        jPanel8.add(jPanel3);
        jPanel3.setBounds(10, 20, 410, 270);

        jButton13.setText("ADD");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton13);
        jButton13.setBounds(530, 110, 90, 40);

        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4);
        jButton4.setBounds(530, 180, 90, 40);

        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5);
        jButton5.setBounds(650, 180, 90, 40);

        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2);
        jButton2.setBounds(650, 110, 90, 40);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(170, 90, 810, 490);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void DisplayTable(){
        try {
            String query ="SELECT * FROM promotions ";
            PreparedStatement ps=null;
            ResultSet rs=null;
            
            ps=DBConnection.con().prepareStatement(query);
            rs=ps.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(CUSTOMER.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
                PreparedStatement ps= null;
                ResultSet rs= null;
                String ItemName=String.valueOf(jComboBox1.getSelectedItem());
                String code=jTextField4.getText();
                SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
                String frm=sdf.format(jDateChooser1.getDate());
                String till=sdf.format(jDateChooser2.getDate());
                String newPrice=jTextField1.getText();
                String Status=String.valueOf(jComboBox2.getSelectedItem());
                
                if(ItemName.equals("") || code.equals("") || frm.equals("") || till.equals("") || newPrice.equals("") || Status.equals("") ){
            JOptionPane.showMessageDialog(this, "Please Fill all Fields!");
            this.setVisible(false);
                }else{
                    try {
                        String query="INSERT INTO `promotions`"+
                                "(`ItemName`, `Code`, `frm`, `till`, `newPrice`,`Status`)"+
                                "VALUES(?,?,?,?,?,?)";
                        ps=DBConnection.con().prepareStatement(query);
                        ps.setString(1,ItemName);
                        ps.setString(2,code);
                        ps.setString(3,frm);
                        ps.setString(4,till);
                        ps.setString(5,newPrice);
                        ps.setString(6,Status);
                        
                         ps.execute();

                    JOptionPane.showMessageDialog(this, "Done!");
                    DisplayTable();
                    jComboBox1.setSelectedItem(null);
                    jComboBox2.setSelectedItem(null);
                    jTextField4.setText(null);
                    jTextField1.setText(null);
                    jDateChooser1.setDate(null);
                    jDateChooser2.setDate(null);
                    
                    } catch (SQLException ex) {
                        Logger.getLogger(Promotions.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
             PreparedStatement ps= null;
                ResultSet rs= null;
                String ItemName=String.valueOf(jComboBox1.getSelectedItem());
                String code=jTextField4.getText();
                SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
                String frm=sdf.format(jDateChooser1.getDate());
                String till=sdf.format(jDateChooser2.getDate());
                String newPrice=jTextField1.getText();
                String Status=String.valueOf(jComboBox2.getSelectedItem());
                
                if(ItemName.equals("") || code.equals("") || frm.equals("") || till.equals("") || newPrice.equals("")|| Status.equals("") ){
            JOptionPane.showMessageDialog(this, "Please Fill all Fields!");
            this.setVisible(false);
                }else{
                 try {
                     String query1= "UPDATE `promotions` SET `frm`=?,`till`=?,`newPrice`=?,`Status`=?WHERE Code=? ";
                     ps=DBConnection.con().prepareStatement(query1);
                     
                     ps.setString(1,frm);
                     ps.setString(2,till);
                     ps.setString(3,newPrice);
                     ps.setString(4,Status);
                     ps.setString(5,code); 
                     ps.execute();
                     DisplayTable();
                    jComboBox1.setSelectedItem(null);
                     jComboBox2.setSelectedItem(null);
                    jTextField4.setText(null);
                    jTextField1.setText(null);
                    jDateChooser1.setDate(null);
                    jDateChooser2.setDate(null);
                 } catch (SQLException ex) {
                     Logger.getLogger(Promotions.class.getName()).log(Level.SEVERE, null, ex);
                 }
                }
                
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
             jComboBox1.setSelectedItem(null);
                    jTextField4.setText(null);
                    jTextField1.setText(null);
                    jDateChooser1.setDate(null);
                    jDateChooser1.setDate(null);
                    jComboBox2.setSelectedItem(null);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try {
            PreparedStatement ps= null;
            ResultSet rs= null;
            
            String query="SELECT * FROM items ";
            ps=DBConnection.con().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
                jComboBox1.addItem(rs.getString("Name"));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Promotions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        try {
            PreparedStatement ps=null;
            ResultSet rs= null;
            
            String sql="SELECT code  FROM items WHERE Name=?";
            ps=DBConnection.con().prepareStatement(sql);
            ps.setString(1, String.valueOf(jComboBox1.getSelectedItem()));
            rs=ps.executeQuery();
            if(rs.next()){
                jTextField4.setText(rs.getString("code"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Promotions.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String a= jTextField4.getText();
            String query ="SELECT  * FROM  `promotions`  WHERE Code = ? ";
            PreparedStatement ps=null;
            ResultSet rs=null;
            ps=DBConnection.con().prepareStatement(query);
            ps.setString(1, a);
            rs=ps.executeQuery();
            if(rs.next()){

                String dte1=(rs.getString("frm"));
                java.util.Date date= new SimpleDateFormat("yyyy-MM-dd").parse(dte1);
                String dte2=(rs.getString("till"));
                java.util.Date date2= new SimpleDateFormat("yyyy-MM-dd").parse(dte2);
               jDateChooser1.setDate(date);
                jDateChooser2.setDate(date2);
                jTextField1.setText(rs.getString("newPrice"));
                jComboBox2.setSelectedItem(rs.getString("newPrice"));
            }
            else{
                JOptionPane.showMessageDialog(this, "Item Not Found!");
                jTextField4.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CUSTOMER.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Promotions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Stocks s = new Stocks();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Items a= new Items();
        this.setVisible(false);
        a.setVisible(true);

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        SalesItems a= new SalesItems();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Reports c= new  Reports();
        this.setVisible(false);
        c.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Promotions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Promotions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Promotions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Promotions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Promotions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
