
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lahiru
 */
public class Stocks extends javax.swing.JFrame {

    /**
     * Creates new form Categories
     */
    public Stocks() {
        initComponents();
    }
    
    public void DisplayTable(){
        try {
            String query ="SELECT * FROM stock";
            PreparedStatement ps=null;
            ResultSet rs=null;
            
            ps=DBConnection.con().prepareStatement(query);
            rs=ps.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(33, 97, 97));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("HEWAGE SUPER");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 20, 320, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(900, 20, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 80);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 142, 142));
        jLabel2.setText("NAVIGATION");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 20, 200, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SALESITEMS");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 50, 110, 20);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(null);

        jButton9.setText("Items");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9);
        jButton9.setBounds(20, 20, 110, 30);

        jButton12.setText("Promotions");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton12);
        jButton12.setBounds(20, 60, 110, 30);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 70, 160, 100);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 160, 570);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STOCK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel8.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Item Name :");
        jPanel8.add(jLabel14);
        jLabel14.setBounds(20, 20, 70, 30);
        jPanel8.add(jTextField7);
        jTextField7.setBounds(460, 20, 220, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Date :");
        jPanel8.add(jLabel15);
        jLabel15.setBounds(380, 120, 70, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Supplier");
        jPanel8.add(jLabel16);
        jLabel16.setBounds(380, 70, 100, 30);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField8);
        jTextField8.setBounds(460, 70, 220, 30);

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4);
        jButton4.setBounds(280, 180, 100, 40);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3);
        jButton3.setBounds(390, 180, 100, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Name", "Item Category", "Brand", "Unit Prize", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel8.add(jScrollPane1);
        jScrollPane1.setBounds(30, 260, 770, 250);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Quantity :");
        jPanel8.add(jLabel4);
        jLabel4.setBounds(20, 70, 80, 30);
        jPanel8.add(jTextField1);
        jTextField1.setBounds(120, 70, 220, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Unit Prize :");
        jPanel8.add(jLabel17);
        jLabel17.setBounds(380, 20, 70, 30);
        jPanel8.add(jDateChooser1);
        jDateChooser1.setBounds(460, 120, 220, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Selling Price :");
        jPanel8.add(jLabel5);
        jLabel5.setBounds(20, 120, 100, 30);
        jPanel8.add(jTextField2);
        jTextField2.setBounds(120, 120, 220, 30);

        jPanel8.add(jComboBox1);
        jComboBox1.setBounds(120, 20, 220, 30);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(170, 90, 810, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Items a= new Items();
          this.setVisible(false);
        a.setVisible(true);
     
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SalesItems a= new SalesItems();
        a.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PreparedStatement ps=null;
        ResultSet rs1=null;
        ResultSet rs2=null;

        String name=String.valueOf(jComboBox1.getSelectedItem());
        String quantity=jTextField1.getText();
        String supplier=jTextField8.getText();
        String unitPrize=jTextField7.getText();
        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(jDateChooser1.getDate());
        String sellingPrice=jTextField2.getText();
        
        double cost=Double.valueOf(unitPrize)*Double.valueOf(quantity);
        String g=String.valueOf(cost);
        

        //String g=String.valueOf(jComboBox1.getSelectedItem());

        if(name.equals("") || quantity.equals("") || supplier.equals("") || unitPrize.equals("") || sellingPrice.equals("") || date.equals("")){
            JOptionPane.showMessageDialog(this, "Please Fill all Fields !");
            
        } else{
            try {
                
                String sql="SELECT * FROM stock WHERE ItemName=?";
                    PreparedStatement ps4=null;
                   ResultSet rs4= null;
                   ps4=DBConnection.con().prepareStatement(sql);
                   ps4.setString(1, name);
                   rs4=ps4.executeQuery();
                   if(rs4.next()){
                       
                       int a=Integer.parseInt(rs4.getString("Quantity"));
                       int quantitynew=a+Integer.valueOf(quantity);
                       //System.out.println(quantitynew);
                       String q2="UPDATE stock SET Quantity=? WHERE ItemName=?";
                       PreparedStatement ps5=null;
                        ResultSet rs5= null;
                        ps5=DBConnection.con().prepareStatement(q2);
                        ps5.setString(1, String.valueOf(quantitynew));
                        ps5.setString(2,name);
                        ps5.executeUpdate();
                        DisplayTable();
                        JOptionPane.showMessageDialog(this,"Added!");
                        jTextField1.setText("");
                    jTextField2.setText("");
                    jComboBox1.setSelectedItem(null);
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jDateChooser1.setDate(null);
                   }else{

                    String query= "INSERT INTO `stock`"
                    +"(`Date`,`ItemName`,`Supplier`,`UnitPrice`,`SellingPrice`,`Quantity`,`Price`)"
                    +"VALUES (?,?,?,?,?,?,?)";
                    ps=DBConnection.con().prepareStatement(query);

                    ps.setString(1,date);
                    ps.setString(2,name);
                    ps.setString(3,supplier);
                    ps.setString(4,unitPrize);
                    ps.setString(5,sellingPrice);
                    ps.setString(6,quantity);
                    ps.setString(7,g);
                    ps.execute();

//                  //Adding to total stocl
//                  String sql="SELECT quantity FROM stockall WHERE ItemName=?";
//                  ps=DBConnection.con().prepareStatement(sql);
//                  ResultSet rs3=null;
//                  ps.setString(1,name);  
//                    rs3=ps.executeQuery();
//                    
//                    int quantityall =Integer.parseInt(rs3.getString("quantity"));
//                    int newQuentity=quantityall+Integer.valueOf(quantity);
//                    
//                   String sql2="UPDATE `stockall` SET  quantity=? WHERE ItemName=?"; 
//                    ps=DBConnection.con().prepareStatement(sql2);
//                    ps.setString(1, String.valueOf(newQuentity));
//                    ps.setString(2, name);
//                   ps.executeUpdate();
                    
                    JOptionPane.showMessageDialog(this, "New Stock has added!");
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jComboBox1.setSelectedItem(null);
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jDateChooser1.setDate(null);
                   }
                } catch (SQLException ex) {
                    Logger.getLogger(CUSTOMER.class.getName()).log(Level.SEVERE, null, ex);
                }
                DisplayTable();
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jComboBox1.setSelectedItem(null);
        jTextField7.setText("");
        jTextField8.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowIconified

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            DisplayTable();
            PreparedStatement ps= null;
            ResultSet rs= null;
            
            String query="SELECT * FROM items ";
            ps=DBConnection.con().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
                jComboBox1.addItem(rs.getString("Name"));  
            }
        } catch (SQLException ex) {
            Logger.getLogger(Stocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Promotions p= new Promotions();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stocks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
